sudo: required
dist: trusty
language: node_js
node_js:
- '6.9.4'
branches:
  only:
    - master
    - develop
addons:
  firefox: latest
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm i process-nextick-args util-deprecate buffer-shims
- npm install
- npm rebuild node-sass # Workaround for https://github.com/yarnpkg/yarn/issues/1981
script:
- npm run lint
- npm run test
after_script:
- npm run coveralls
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop"